### ISSUE TITLE
Set SMTPAutoTLS via config

### ISSUE THREAD

**Issue by barkovrman** [rmrevin/yii2-postman#12]
This module use phpmailer. But now in config we can't set $mailer->SMTPAutoTLS.
Pleas add string
if (isset($this->smtp_config['smtpAutoTls'])) $mailer->SMTPAutoTLS = $this->smtp_config['smtpAutoTls'];

in file rmrevin/yii2-postman/Component.php
Thanks! ))

**Comment by rmrevin** [comment]
Hi, thanks for report. Pull request welcome!

**Comment by barkovrman** [comment]
Ok. I'm created "Pull request" - https://github.com/rmrevin/yii2-postman/pull/13

**Comment by barkovrman** [comment]
Done

**Comment by rmrevin** [comment]
Thanks, merged.
