### ISSUE TITLE
When install with Composer get error.

### ISSUE THREAD

**Issue by igorrebega** [rmrevin/yii2-postman#2]
Class rmrevin\yii\postman\Postman does not exist

my config is:

'postman' => [
            'class' => 'rmrevin\yii\postman\Postman',

**Comment by igorrebega** [comment]
I solved problem when change configuration to

'class' => 'rmrevin\yii\postman\Component',

**Comment by rmrevin** [comment]
Thank U. Really a bug in the documentation. Fixed.

**Comment by igorrebega** [comment]
Не за что)
