### ISSUE TITLE
Add to installing instruction migration instruction

### ISSUE THREAD

**Issue by igorrebega** [rmrevin/yii2-postman#3]
Add to installing instruction migration instruction

**Comment by igorrebega** [comment]
php yii migrate/up --migrationPath=@vendor/rmrevin/yii2-postman/migrations/ dont work. Error Unknown component ID: postman

**Comment by rmrevin** [comment]
In the configuration console application no component postman

**Comment by rmrevin** [comment]
Migration can be copied. While yii not support the migration of the modules. Later, they must be supported natively. You can also pay attention to the extension https://github.com/dmstr/yii2-migrate-command

**Comment by igorrebega** [comment]
Yeah, realy. But, i think that you can add this to installing part of your aplication

**Comment by rmrevin** [comment]
Of Course. Should be supplemented. Can do pull pull request with additions.

**Comment by rmrevin** [comment]
Fixed.
